### ISSUE TITLE
Bug: Exporting mission as SQF no longer works.

### ISSUE THREAD

**Issue by L-McKendrick** [R3voA3/3den-Enhanced#198] opened 2021-06-05 21:11 UTC
Reproducible with no other mods loaded.

Place any object or unit. Save mission and attempt to export as SQF. Game just prints error 

`!=# objects simulated
Generic error in expression`

This bug has been happening since the latest update.

**Comment by R3voA3** [comment] 2021-06-05 23:03
Found the cause. It's a BI bug. Ticket is up https://feedback.bistudio.com/T158949

I am gonna remove the attribute which causes that temporarily. Thanks again for the report.

**Comment by R3voA3** [comment] 2021-06-06 08:19
I've just pushed an updated which removes the attribute which causes this temporarily until the issue is fixed in Arma 3.

**Closed** 2021-06-07 13:05 UTC
Labels: bug, finished
